languageCode = "it"
languageName = "Italiano"
weight = 1
title = "U-GO"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "SAVE OUR DEGREES"

[params.author]
  name = "U-GO"
  image = "img/blowfish_logo.png"
  headline = "SAVE OUR DEGREES"
  bio = "SAVE OUR DEGREES"
  links = [
    {  instagram = "https://www.instagram.com/ugo_abarc/" },
    { tiktok = "https://www.tiktok.com/@ugo_abarc" },
  ]